### ISSUE TITLE
Handling a negative maximum length

### ISSUE THREAD

**Issue by surfer190** [matriphe/mssql2mysql#3]
I noticed that for a particular field a value of `-1` was returned from the `information_schema` query for `$row['CHARACTER_MAXIMUM_LENGTH']`.

The resulting `mysql create` script was trying to create a field of negative length.
To handle this I suggest:

```
if ($row['CHARACTER_MAXIMUM_LENGTH'] < 0){
                            $row['CHARACTER_MAXIMUM_LENGTH'] = 255;
                        }
```

What is you opinion?

**Comment by matriphe** [comment]
Hmm.. I've never found this. I think it's a good patch. :D

**Comment by matriphe** [comment]
Done, @surfer190
